### PR TITLE
Fix zlib library name (again)

### PR DESCRIPTION
**Pull request by pema99**
As discussed 

https://github.com/jkvargas/russimp-sys/pull/38#issuecomment-1909053196

### CODE REVIEW

**Comment by jkvargas** [comment]
hey man,
thanks for your contribution.
So, before I can merge your fix, we need to have all the steps passing =)

**Comment by pema99** [comment]
Hmm. Maybe you were right about the linux issue? I double checked the name of the library in the linux zip file, and it is indeed "libzlibstatic.a", but I guess the linker on linux might be adding the "static" part automatically or something? I'm not really familiar enough with linux to know, but I can try guarding based on the platform, second.

**Comment by pema99** [comment]
Let's see if that does it

**Comment by jkvargas** [comment]
thanks, mate =)

**Pull request merged**
